# Configuration related to self-hosted runner.
self-hosted-runner:
  # Labels of self-hosted runner in array of strings.
  labels:
    - 1cpu-linux-arm64
    - self-hosted
    - runner=1cpu-linux-arm64
    - runner=linux-multi-gpu
