// Code generated by sdkgen. DO NOT EDIT.
/**
 * Client configuration for generated service clients.
 */
export type ClientConfig = {
  baseURL?: string;
  accessKey?: string;
  pathPrefix?: string;
  timeoutMs?: number;
  maxRetries?: number;
};

const defaultGatewayURL = "http://search-service";

export class HTTPError extends Error {
  constructor(public readonly status: number, public readonly payload: unknown) {
    super("HTTP " + status + ": " + JSON.stringify(payload));
  }
}

/**
 * HTTP client used by generated API operation wrappers.
 */
export class Client {
  readonly baseURL: string;
  readonly accessKey: string;
  readonly pathPrefix: string;
  readonly timeoutMs: number;
  readonly maxRetries: number;

  /**
   * Creates a new client with environment-aware defaults.
   */
  constructor(config: ClientConfig = {}) {
    this.baseURL = config.baseURL ?? process.env.GATEWAY_URL ?? defaultGatewayURL;
    this.accessKey = config.accessKey ?? process.env.ACCESS_KEY ?? "";
    this.pathPrefix = config.pathPrefix ?? "search";
    this.timeoutMs = config.timeoutMs ?? 10_000;
    this.maxRetries = config.maxRetries ?? 3;
  }

  /**
   * Executes a request and deserializes the response body as JSON.
   */
  async request<T>(method: string, path: string, query?: Record<string, unknown>, body?: unknown): Promise<T> {
    const url = new URL(this.baseURL.replace(/\/$/, "") + this.pathPrefix + path);
    if (query) {
      for (const [k, v] of Object.entries(query)) {
        if (v === undefined || v === null || v === "") continue;
        url.searchParams.set(k, String(v));
      }
    }

    let lastErr: unknown;
    for (let attempt = 0; attempt <= this.maxRetries; attempt++) {
      try {
        const controller = new AbortController();
        const timer = setTimeout(() => controller.abort(), this.timeoutMs);
        const res = await fetch(url, {
          method,
          signal: controller.signal,
          headers: {
            "Content-Type": "application/json",
            ...(this.accessKey ? { Authorization: "Bearer " + this.accessKey } : {}),
          },
          body: body === undefined ? undefined : JSON.stringify(body),
        });
        clearTimeout(timer);

        if (!res.ok) {
          if (res.status >= 500 && attempt < this.maxRetries) {
            await sleep(100 * (attempt + 1));
            continue;
          }
          const payload = await safeJSON(res);
          throw new HTTPError(res.status, payload);
        }

        if (res.status === 204) return undefined as T;
        return (await res.json()) as T;
      } catch (err) {
        lastErr = err;
        if (attempt >= this.maxRetries) throw err;
      }
    }
    throw lastErr;
  }

  /**
   * Opens an SSE endpoint and yields each decoded event payload line.
   */
  async *sse(path: string, query?: Record<string, unknown>): AsyncGenerator<string, void, void> {
    const url = new URL(this.baseURL.replace(/\/$/, "") + this.pathPrefix + path);
    if (query) {
      for (const [k, v] of Object.entries(query)) {
        if (v === undefined || v === null || v === "") continue;
        url.searchParams.set(k, String(v));
      }
    }
    const res = await fetch(url, {
      method: "GET",
      headers: {
        Accept: "text/event-stream",
        ...(this.accessKey ? { Authorization: "Bearer " + this.accessKey } : {}),
      },
    });
    if (!res.ok || !res.body) {
      throw new HTTPError(res.status, await safeJSON(res));
    }
    const decoder = new TextDecoder();
    const reader = res.body.getReader();
    let buffer = "";
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      let idx = buffer.indexOf("\n");
      while (idx >= 0) {
        const line = buffer.slice(0, idx).trim();
        buffer = buffer.slice(idx + 1);
        if (line.startsWith("data:")) {
          yield line.slice(5).trim();
        }
        idx = buffer.indexOf("\n");
      }
    }
  }
}

/**
 * Simple async sleep used between retry attempts.
 */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Best-effort response body parsing for non-success payloads.
 */
async function safeJSON(res: Response): Promise<unknown> {
  try {
    return await res.json();
  } catch {
    return await res.text();
  }
}

