// Code generated by sdkgen. DO NOT EDIT.
/**
 * Article returned in search and retrieval responses.
 */
export interface Article {
  /**
   * Authors credited for this article.
   */
  authors?: Author[];
  /**
   * Regions where the article is available
   */
  availabilityRegions: string[];
  /**
   * One of: `sports`, `entertainment`.
   */
  contentType: "entertainment" | "sports";
  /**
   * RFC 3339 UTC datetime when the article was created
   */
  createdAt: string;
  /**
   * Viaplay player embed URL for this article
   */
  embedUrl?: string;
  /**
   * UUID of the article
   */
  id: string;
  /**
   * ISO language code. One of: `sv`, `da`, `fi`, `nl`, `no`
   */
  language: string;
  /**
   * Picture assets attached to this article.
   */
  pictures?: Picture[];
  /**
   * Short lead paragraph shown above the body.
   */
  preamble?: string;
  /**
   * RFC 3339 UTC datetime when the article is/was published
   */
  publishedAt?: string;
  /**
   * Short headline for feed/ticker/push surfaces. Falls back to title when absent.
   */
  shortTitle?: string;
  /**
   * URL-friendly unique identifier
   */
  slug: string;
  tags: Taxonomy;
  /**
   * Main body text of the article
   */
  text: string;
  /**
   * Headline of the article
   */
  title: string;
  /**
   * RFC 3339 UTC datetime when the article was last updated
   */
  updatedAt?: string;
  /**
   * Video assets attached to this article.
   */
  videos: Video[];
}
/**
 * HAL response data fields (from GetMap):
 */
export type ArticleCollection = Record<string, unknown>;
/**
 * Generated model type for `AuthenticationResponse`.
 */
export interface AuthenticationResponse {
  /**
   * Access token.
   */
  accessToken: string;
  /**
   * Expiry epoch seconds of the access token.
   */
  accessTokenExpiryEpochSeconds: number;
  /**
   * Refresh token.
   */
  refreshToken: string;
}
/**
 * list of authors credited for this article.
 */
export interface Author {
  /**
   * author's email address
   */
  email: string;
  /**
   * author's full name
   */
  name: string;
}
/**
 * Generated model type for `EntertainmentTags`.
 */
export interface EntertainmentTags {
  episode: TranslationTags;
  format: TranslationTags;
  /**
   * Season identifier (a single string, not an array).
   */
  seasons: string;
}
/**
 * Generated model type for `ErrBadRequest`.
 */
export interface ErrBadRequest {
  error: { errCode: string; message: string };
}
/**
 * Generated model type for `ErrForbidden`.
 */
export interface ErrForbidden {
  error: { errCode: string; message: string };
}
/**
 * Generated model type for `ErrInternal`.
 */
export interface ErrInternal {
  error: { errCode: string; message: string };
}
/**
 * Generated model type for `ErrNotFound`.
 */
export interface ErrNotFound {
  error: { errCode: string; message: string };
}
/**
 * Generated model type for `ErrUnAuthorized`.
 */
export interface ErrUnAuthorized {
  error: { errCode: string; message: string };
}
/**
 * Generated model type for `ErrUserAuthenticationFailed`.
 */
export interface ErrUserAuthenticationFailed {
  count: number;
  errCode: string;
  message: string;
  statusCode: number;
}
/**
 * Generated model type for `ErrValidation`.
 */
export interface ErrValidation {
  error: { details?: Record<string, unknown>[]; errCode: string; message: string };
}
/**
 * Generated model type for `PartnerAvailability`.
 */
export interface PartnerAvailability {
  availableFrom?: string;
  availableTo?: string;
  partnerId: string;
}
/**
 * Generated model type for `Picture`.
 */
export interface Picture {
  /**
   * picture media-guid
   */
  mediaGuid?: string;
  /**
   * picture text description of the image
   */
  pictureText?: string;
  /**
   * picture URL of the image
   */
  url: string;
}
/**
 * Generated model type for `Poster`.
 */
export interface Poster {
  /**
   * large variation of the poster
   */
  large: string;
  /**
   * medium variation of the poster
   */
  medium: string;
  /**
   * small variation of the poster
   */
  small: string;
}
/**
 * Generated model type for `SportTags`.
 */
export interface SportTags {
  /**
   * Primary competition(s) for the article.
   */
  competitions: TranslationTags[];
  /**
   * mahle (array[string], required) - Participant IDs or names (free-form strings, not translation objects).
   */
  participants?: string;
  /**
   * Primary sport(s) for the article.
   */
  sports: TranslationTags[];
  /**
   * Teams covered by the article.
   */
  teams: TranslationTags[];
  /**
   * Types of sport-related videos.
   */
  videoTypes: string[];
}
/**
 * Generated model type for `StatusError`.
 */
export interface StatusError {
  errCode: "authentication_required" | "resource_not_found" | "invalid_request" | "validation_failed" | "resource_conflict" | "user_authentication_failed" | "api_authentication_failed" | "internal_server_error";
  message: string;
}
/**
 * Generated model type for `Taxonomy`.
 */
export interface Taxonomy {
  /**
   * Content category labels.
   */
  contents?: string[];
  /**
   * Free-text tags. Always present in responses (may be empty).
   */
  freeTexts: string[];
}
/**
 * Generated model type for `TranslationTags`.
 */
export interface TranslationTags {
  /**
   * Internal stable ID (slug-like).
   */
  id: string;
  /**
   * External Opta ID, when one was supplied via the legacy `"opta"` locale. Opaque upstream identifier — do not assume any particular shape.
   */
  optaId?: string;
  /**
   * Flat map of ISO 639-1 language code → translated display name. Only languages that have a translation are present as keys.
   */
  translations: { da?: string; no?: string; sv?: string };
}
/**
 * Generated model type for `ValidationErrMsg`.
 */
export interface ValidationErrMsg {
  code: "required" | "invalid_enum_value" | "invalid_url" | "invalid_ulid" | "invalid_uuid" | "invalid_email" | "must_match_discriminator" | "invalid_sort_field" | "invalid";
  message: string;
  path: string;
}
/**
 * Generated model type for `Video`.
 */
export interface Video {
  /**
   * Horizontal (landscape) video variant. Present only when a horizontal asset is available.
   */
  horizontal?: VideoVariant | unknown;
  /**
   * video unique identifier for the logical video,
   */
  id: string;
  /**
   * Vertical (portrait) video variant. Present only when a vertical asset is available.
   */
  vertical?: VideoVariant | unknown;
}
/**
 * Generated model type for `VideoVariant`.
 */
export interface VideoVariant {
  /**
   * video duration in seconds
   */
  duration?: number;
  /**
   * video filename
   */
  filename?: string;
  /**
   * video format one of `mp4` `webm` `ogg`
   */
  format?: string;
  /**
   * mpx media-guid
   */
  mediaGuid: string;
  posterUrls?: Poster;
}
