// Code generated by sdkgen. DO NOT EDIT.
import { API as SearchAPI, Client as SearchClient, type ClientConfig as SearchClientConfig } from "./service/search/index";

export interface SDKConfig {
  /**
   * Shared client settings applied to all services unless a service override is provided.
   */
  default?: Record<string, unknown>;
  /**
   * Optional per-service client override for `search`.
   */
  search?: SearchClientConfig;
}

/**
 * Unified entrypoint that exposes all service clients.
 */
export class SDK {
  /**
   * `search` service API.
   */
  readonly search: SearchAPI;

  /**
   * Creates a unified SDK with shared client configuration.
   */
  constructor(config: SDKConfig = {}) {
    const shared = config.default ?? {};
    this.search = new SearchAPI(new SearchClient({
      ...(shared as SearchClientConfig),
      ...(config.search ?? {}),
    }));
  }
}
